on:
  push:

  workflow_dispatch:

jobs:
  job1:
    runs-on: self-hosted

    steps:
      - run: |
          echo $PWD
          ls -la
          cd ..
          ls -la

          cd ..
          ls-la
      
      - run: git --version
        continue-on-error: true
        
      - run: node --version
        continue-on-error: true
        
      - run: dotnet --version
        continue-on-error: true
